### ISSUE TITLE
Implement schedule re-design

### ISSUE THREAD

**Issue by aldahick** [MAC-IUPUI/node-site#15]
The schedule UI needs to be rewritten to reflect some design changes. This is still a WIP.

[Schedule-UI.pdf](https://github.com/MAC-IUPUI/node-site/files/225035/Schedule-UI.pdf)

**Comment by Tiin57** [comment]
There are several questions regarding the design (which I'm posting here to aid my memory).

- Time body (the colorful bit): Should this be scrollable, since we are open longer than 6 hours? If not, how should we handle that?

- Colors: The original design was to distinguish tutors and graduates. Since we now have the MAC and MAC Stat, the colors and purpose behind them has been obsoleted. Should we use different colors or the same, and should we have text in the colored areas to distinguish other factors?

There may be other things that I'm not remembering. Might add them later.

**Comment by Tiin57** [comment]
I'm reassigning this to @LDBrown because he's going to have more fun implementing this than I am. This should be finished by 4/29/16.

**Comment by aldahick** [comment]
Since @LDBrown will be out of the country starting May 16, this (and misc. features/fixes) are priority until then.
